version: '3.0'
services:
  jms:
    image: vromero/activemq-artemis
    ports:
      - 8161:8161
      - 61616:61616
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - /Users/johnkruidhof/Projects/Java/Docker/persistence/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
  eureka:
    image: johnkruidhof/mssc-brewery-eureka
    ports:
      - 8761:8761
  config:
    image: johnkruidhof/mssc-config-server
    ports:
      - 8888:8888
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER-IP-ADDRESS: 'true'
  inventory-service:
    image: johnkruidhof/mssc-beer-inventory-service
    ports:
      - 8081:8081
    depends_on:
      - eureka
      - config
      - jms
      - mysql
      - zipkin
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER-IP-ADDRESS: 'true'
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_PROFILES_ACTIVE: docker-secure,local-discovery
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
      SPRING_ARTEMIS_HOST: jms
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/beerinventoryservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    restart: on-failure
  beer-service:
    image: johnkruidhof/mssc-beer-service
    ports:
      - 8082:8082
    depends_on:
      - eureka
      - config
      - jms
      - mysql
      - zipkin
      - inventory-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER-IP-ADDRESS: 'true'
      SFG_BREWERY_BEER-INVENTORY-SERVICE-HOST: http://inventory-service:8081
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_PROFILES_ACTIVE: docker-secure,local-discovery
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
      SPRING_ARTEMIS_HOST: jms
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/beerservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    restart: on-failure
  order-service:
    image: johnkruidhof/mssc-beer-order-service
    ports:
      - 8083:8083
    depends_on:
      - eureka
      - config
      - jms
      - mysql
      - zipkin
      - beer-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER-IP-ADDRESS: 'true'
      #      SFG_BREWERY_BEER-SERVICE-HOST: http://host.docker.internal:8082
      SFG_BREWERY_BEER-SERVICE-HOST: http://beer-service:8082
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_PROFILES_ACTIVE: docker-secure,local-discovery
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
      SPRING_ARTEMIS_HOST: jms
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/beerorderservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    restart: on-failure
  inventory-failover:
    image: johnkruidhof/mssc-inventory-failover
    ports:
      - 8084:8084
    depends_on:
      - eureka
      - config
      - zipkin
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER-IP-ADDRESS: 'true'
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_PROFILES_ACTIVE: local-discovery
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
    restart: on-failure
  gateway:
    image: johnkruidhof/mssc-brewery-gateway
    ports:
    - 9090:9090
    depends_on:
      - eureka
      - config
      - inventory-service
      - beer-service
      - order-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER-IP-ADDRESS: 'true'
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_PROFILES_ACTIVE: local-discovery
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
    restart: on-failure
